### ISSUE TITLE
make -j2

### ISSUE THREAD

**Issue by Jessica0496** [dpfried/rnng-bert#1]
when I run: make -j2
make:*** No targets specified and no makefile found.  Stop.

**Comment by Jessica0496** [comment]
CMake Error at cmake/FindEigen3.cmake:33 (file):
  file failed to open for reading (No such file or directory):

**Comment by dpfried** [comment]
Could you check to make sure that you've installed Eigen, are passing the Eigen root directory as the -DEIGEN3_INCLUDE_DIR argument to cmake, and that CMakeLists.txt is present in this directory?

(and sorry for the very delayed response!)
