### ISSUE TITLE
cannot compile on apple m1 chip

### ISSUE THREAD

**Issue by Mercurium-9** [dpfried/rnng-bert#2]
Hi! It seems mac with m1 chip cannot compile the parser due to tensorflow c library issue: there is not c library available for arm64 architecture. Could you please let me know if there is any way to run the parser on m1 chip? Thanks a lot!

BTW, it is hard (at least I didn't succeed) to use tensorflow 2.8.0 c api to compile the parser, as there is no function TF_StringEncode available, which seems to be a common issue for all TF after 2.4.0. Compiling a tensorflow 1.12 c library is also tricky, as it seems to ask for very old bazel version (which is not even downloadable) to provide relevant dependencies. I would really appreciate it if there are some suggestions to circumvent these issues!

**Comment by dpfried** [comment]
Hi, sorry about the troubles setting this up. I haven't worked on this codebase for several years and so haven't been maintaining it.

For the m1 chip question -- I'm not sure, sorry. You might need to open an issue on the tensorflow repository.

We've only tested the parser with tensorflow 1, and I'm not sure whether it will be possible to get it to work with 2. You might also need to file an issue with tensorflow about how to compile tensorflow 1.12 given that the very old bazel version isn't downloadable.

An alternative could be to update the RNNG code to work with newer versions of tensorflow, but I unfortunately don't have bandwidth myself these days to work on this. If you're able to get it to work a pull request would definitely be appreciated!

If you're just looking for a strong constituency parser, I'd suggest using Nikita Kitaev's chart parser, https://github.com/nikitakit/self-attentive-parser which has stronger performance than this RNNG parser (Nikita has updated the chart parser to use stronger pretrained models) and is probably much easier to set up.

Sorry to not have a more useful answer for you!

Daniel

**Comment by Mercurium-9** [comment]
Hi Daniel, thanks for the quick response! I'll check the self attentive parser as suggested!
